name: CI

on:
    workflow_dispatch:

jobs:
    go-ci:
        uses: koprivicaa/gha-playground/workerpool/.github/workflows/reusable-go.yml@main
        with:
            go-version: "1.22"
            coverage-threshold: 80
        secrets:
            GH_PAT: ${{ secrets.GH_PAT }}
