name: deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  aws-auth-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::472506472772:role/github-actions-role
          aws-region: eu-central-1

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: List S3 buckets
        run: aws s3 ls

      - name: Upload file to S3
        run: |
            echo "hello oidc" > demo.txt
            aws s3 cp demo.txt s3://gha-playground-demo/demo.txt